src: support arrays of licenses in license field
Currently if a project specifies multiple licenses as an array the
following error will be reported:

return value === undefined || value === '' || value.toUpperCase() ===
unknown;
                                                      ^
TypeError: value.toUpperCase is not a function
    at check
(/bucharest-gold/license-reporter/lib/unknown.js:37:55)
    at unknownCheck
(/bucharest-gold/license-reporter/lib/unknown.js:21:10)
    at project.licenses.license.filter
(/bucharest-gold/license-reporter/lib/unknown.js:8:9)
    at Array.filter (native)
    at Object.module.exports.check
(/bucharest-gold/license-reporter/lib/unknown.js:6:35)
    at Test.test
(/bucharest-gold/license-reporter/test/unknown-test.js:20:48)
    at Test.bound [as _cb]
(/bucharest-gold/license-reporter/node_modules/tape/lib/test.js:64:32)
    at Test.run
(/bucharest-gold/license-reporter/node_modules/tape/lib/test.js:83:10)
    at Test.bound [as run]
(/bucharest-gold/license-reporter/node_modules/tape/lib/test.js:64:32)
    at Immediate.next [as _onImmediate]
(/bucharest-gold/license-reporter/node_modules/tape/lib/results.js:71:15)

While I have to double check the issue repored in #84 I'm adding a Fixes
as I suspect the same error migth be causing this. I run the tool
against the same repository and not been able to reproduce the exact
error and with this commit I don't get any errors.

Fixes: https://github.com/bucharest-gold/license-reporter/issues/84